### ISSUE TITLE
Unstable sort in LAMBDAMART

### ISSUE THREAD

**Issue by sycbelief** [hpclab/quickrank#4]
I ran LAMBDAMART using  quickrank and ranklib respectively and found the latter one a little better. 
I read the code and find in /src/data/queryresults.cc Line 52:

> std::sort(dest, dest + num_results_, comp); 

use unstable sort which cause the little difference. 
Change std::sort to std::stable_sort and the two results become the same.

**Comment by claudio-lucchese** [comment]
This is due to how ties are broken in a ranked list.
Unfortunately, most algorithms, such as QuickRank and RankLib,
might be affected by the input data order, and this is not a desirable property.

We preferred not to mimic RankLib behaviour, which is dependent on the input data order.
On the one hand, we decided to use std::sort as it is more efficient than std:stable_sort.
On the other hand, we implemented the TiedNDCG metric, which is slower than NDCG, but it properly brakes ties independently of the input data order.

Thanks for your interest in QuickRank.
